### ISSUE TITLE
comparison updates

### ISSUE THREAD

**Issue by arska** [amazeeio/docs#60]
- update number of locations, list of countries
- fully open source (dockerfiles, templates, lagoon, docker, kubernetes, openshift)
- PHP 5.6, 7.0, 7.1, 7.2
- Node.js 6, 8
- Apache Solr 3, 5, 6
- available DB-backends: mysql/mariadb, Elasticsearch, Redis, Memcached, MongoDB
- bring your own docker container

**Comment by rtprio** [comment]
```

**Comment by dasrecht** [comment]
Closing - As we start to migrate towards lagoon we might create a new comparison overview
