### ISSUE TITLE
step-by-step instructions for getting drupal-demo working locally

### ISSUE THREAD

**Issue by arska** [amazeeio/docs#61]
mac/linux: install docker/pygmy, windows: install cachealot, then:
git clone git@github.com:amazeeio/drupal-example.git # or make your own fork first to be able to do webhook later ?
cd drupal-example
pygmy up
docker run --rm -it -v $PWD:/app composer install
docker-compose up -d
docker-compose exec cli bash -c "cd web ; drush si config_installer -y --account-name=admin --account-pass=admin install_configure_form.enable_update_status_module=NULL install_configure_form.enable_update_status_emails=NULL"

#demo
docker-compose exec cli bash -c "cd web; drush --uri=drupal.docker.amazee.io uli"
# home, structure, block layout
# move "site branding" druplicon from breadcrumb to header
# save 
docker-compose exec cli bash -c "cd web && drush -y cex"
git status
git checkout -b aarnos-featurebranch
git commit -am "change druplicon"
git push origin aarnos-featurebranch
#check slack

#cleanup
git checkout master && git branch -D aarnos-featurebranch && git push -d origin aarnos-featurebranch
docker-compose exec cli bash -c "cd web && drush -y cim"

**Comment by dasrecht** [comment]
closing as we're moving towards lagoon
