### ISSUE TITLE
Chapter "Grant amazee.io access to your git repository" outdated for Gitlab

### ISSUE THREAD

**Issue by dmsmidt** [amazeeio/docs#63]
The screenshots and guide for setting up the access and webhooks on Gitlab are outdated.

**Comment by dasrecht** [comment]
closing this - as we start to move towards [lagoon](https://github.com/amazeeio/lagoon) new documentation will be written on this.

We already started on it

- [Code access](http://lagoon.readthedocs.io/en/stable/using_lagoon/setup_project/#2-provide-access-to-your-code)
- [Webhook configuration](http://lagoon.readthedocs.io/en/stable/using_lagoon/configure_webhooks/)
